package project_templates

import (
	"fmt"

	"github.com/ozacod/cpx/internal/templates"
)

func init() {
	RegisterTemplate(&SFMLTemplate{})
}

// SFMLTemplate generates an SFML multimedia application
type SFMLTemplate struct {
	BaseTemplateHelper
}

func (t *SFMLTemplate) Name() string {
	return "SFML"
}

func (t *SFMLTemplate) Description() string {
	return "Multimedia application with SFML library"
}

func (t *SFMLTemplate) Dependencies() []string {
	return []string{"sfml"}
}

func (t *SFMLTemplate) Generate(config TemplateConfig) error {
	projectName := config.ProjectName

	// Create directory structure
	dirs := []string{
		"include/" + projectName,
		"src",
		"assets",
		"docs",
	}
	if err := t.CreateProjectStructure(projectName, dirs); err != nil {
		return err
	}

	// Generate main.cpp
	mainCpp := t.generateMainCpp(projectName)
	if err := t.WriteFile(projectName, "src/main.cpp", mainCpp); err != nil {
		return err
	}

	// Generate version header
	versionHpp := templates.GenerateVersionHpp(projectName, "0.1.0")
	if err := t.WriteFile(projectName, "include/"+projectName+"/version.hpp", versionHpp); err != nil {
		return err
	}

	// Generate build system files (vcpkg only)
	cmakeLists := t.generateCMakeLists(projectName, config.CppStandard)
	if err := t.WriteFile(projectName, "CMakeLists.txt", cmakeLists); err != nil {
		return err
	}
	if err := t.SetupVcpkg(projectName, t.Dependencies()); err != nil {
		return fmt.Errorf("failed to setup vcpkg: %w", err)
	}

	// Generate common files
	if err := t.GenerateCommonFiles(config); err != nil {
		return err
	}

	// Generate README
	readme := t.generateReadme(projectName)
	if err := t.WriteFile(projectName, "README.md", readme); err != nil {
		return err
	}

	// Initialize git
	_ = t.InitGitRepo(projectName)

	t.PrintSuccess(projectName)
	return nil
}

func (t *SFMLTemplate) generateMainCpp(projectName string) string {
	return fmt.Sprintf(`// %s - SFML Application
// Generated by cpx

#include <SFML/Graphics.hpp>
#include <SFML/Window.hpp>
#include <cmath>
#include <cstdint>

int main() {
    // Create window (SFML 3.x API)
    sf::RenderWindow window(sf::VideoMode({800, 600}), "%s");
    window.setFramerateLimit(60);

    // Create shapes
    sf::CircleShape circle(50.f);
    circle.setFillColor(sf::Color::Red);
    circle.setPosition({375.f, 275.f});
    circle.setOrigin({50.f, 50.f});

    sf::RectangleShape rectangle({100.f, 60.f});
    rectangle.setFillColor(sf::Color::Blue);
    rectangle.setPosition({100.f, 100.f});

    // Animation variables
    float time = 0.f;
    sf::Clock clock;

    // Main loop
    while (window.isOpen()) {
        // Event handling (SFML 3.x style)
        while (const std::optional event = window.pollEvent()) {
            if (event->is<sf::Event::Closed>()) {
                window.close();
            }
            if (const auto* keyPressed = event->getIf<sf::Event::KeyPressed>()) {
                if (keyPressed->code == sf::Keyboard::Key::Escape) {
                    window.close();
                }
            }
        }

        // Update
        float dt = clock.restart().asSeconds();
        time += dt;

        // Animate circle (pulsing and color changing)
        float scale = 1.0f + 0.2f * std::sin(time * 3.0f);
        circle.setScale({scale, scale});

        std::uint8_t r = static_cast<std::uint8_t>(128 + 127 * std::sin(time * 2.0f));
        std::uint8_t g = static_cast<std::uint8_t>(128 + 127 * std::sin(time * 2.5f));
        std::uint8_t b = static_cast<std::uint8_t>(128 + 127 * std::sin(time * 3.0f));
        circle.setFillColor(sf::Color(r, g, b));

        // Animate rectangle (rotating)
        rectangle.rotate(sf::degrees(60.f * dt));

        // Render
        window.clear(sf::Color(30, 30, 40));
        window.draw(rectangle);
        window.draw(circle);
        window.display();
    }

    return 0;
}
`, projectName, projectName)
}

func (t *SFMLTemplate) generateCMakeLists(projectName string, cppStandard int) string {
	return fmt.Sprintf(`cmake_minimum_required(VERSION 3.16)
project(%s VERSION 0.1.0 LANGUAGES CXX)

set(CMAKE_CXX_STANDARD %d)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)

# Find SFML 3.x (no separate system component)
find_package(SFML COMPONENTS Network Graphics Window Audio CONFIG REQUIRED)

# Add executable
add_executable(${PROJECT_NAME}
    src/main.cpp
)

target_include_directories(${PROJECT_NAME} PRIVATE
    ${CMAKE_CURRENT_SOURCE_DIR}/include
)

# Link against SFML 3.x namespaced targets
target_link_libraries(${PROJECT_NAME} PRIVATE
    SFML::Graphics
    SFML::Window
)

# Copy compile_commands.json to project root
if(CMAKE_EXPORT_COMPILE_COMMANDS)
    add_custom_target(copy_compile_commands ALL
        ${CMAKE_COMMAND} -E copy_if_different
        ${CMAKE_BINARY_DIR}/compile_commands.json
        ${CMAKE_SOURCE_DIR}/compile_commands.json
    )
endif()
`, projectName, cppStandard)
}

func (t *SFMLTemplate) generateReadme(projectName string) string {
	return fmt.Sprintf(`# %s

A multimedia application built with SFML (Simple and Fast Multimedia Library).

## Building

`+"```"+`bash
cpx build
`+"```"+`

## Running

`+"```"+`bash
cpx run
`+"```"+`

## Features

- Window with 60 FPS frame limiting
- Animated circle with pulsing effect
- Color-changing shapes
- Rotating rectangle
- Event handling (keyboard, window close)

## Controls

- **ESC**: Exit application

## Dependencies

- SFML (Graphics, Window, System)

## SFML Modules

SFML provides several modules:
- **System**: Vectors, time, threads
- **Window**: Window management, input
- **Graphics**: 2D rendering, shapes, sprites
- **Audio**: Sound, music playback
- **Network**: TCP/UDP sockets

## License

MIT
`, projectName)
}
