package project_templates

import (
	"fmt"

	"github.com/ozacod/cpx/internal/pkg/templates"
)

func init() {
	RegisterTemplate(&SFMLTemplate{})
}

// SFMLTemplate generates an SFML multimedia application
type SFMLTemplate struct {
	BaseTemplateHelper
}

func (t *SFMLTemplate) Name() string {
	return "SFML"
}

func (t *SFMLTemplate) Description() string {
	return "Multimedia application with SFML library"
}

func (t *SFMLTemplate) Dependencies() []string {
	return []string{"sfml"}
}

func (t *SFMLTemplate) Generate(config TemplateConfig) error {
	projectName := config.ProjectName

	// Create directory structure
	dirs := []string{
		"include/" + projectName,
		"src",
		"assets",
		"docs",
	}
	if err := t.CreateProjectStructure(projectName, dirs); err != nil {
		return err
	}

	// Generate main.cpp
	mainCpp := t.generateMainCpp(projectName)
	if err := t.WriteFile(projectName, "src/main.cpp", mainCpp); err != nil {
		return err
	}

	// Generate version header
	versionHpp := templates.GenerateVersionHpp(projectName, "0.1.0")
	if err := t.WriteFile(projectName, "include/"+projectName+"/version.hpp", versionHpp); err != nil {
		return err
	}

	// Generate build system files (vcpkg only)
	cmakeLists := t.generateCMakeLists(projectName, config.CppStandard)
	if err := t.WriteFile(projectName, "CMakeLists.txt", cmakeLists); err != nil {
		return err
	}
	cmakePresets := templates.GenerateCMakePresets()
	if err := t.WriteFile(projectName, "CMakePresets.json", cmakePresets); err != nil {
		return err
	}
	if err := t.SetupVcpkg(projectName, t.Dependencies()); err != nil {
		return fmt.Errorf("failed to setup vcpkg: %w", err)
	}

	// Generate common files
	if err := t.GenerateCommonFiles(config); err != nil {
		return err
	}

	// Generate README
	readme := t.generateReadme(projectName)
	if err := t.WriteFile(projectName, "README.md", readme); err != nil {
		return err
	}

	// Initialize git
	_ = t.InitGitRepo(projectName)

	t.PrintSuccess(projectName)
	return nil
}

func (t *SFMLTemplate) generateMainCpp(projectName string) string {
	return fmt.Sprintf(`// %s - SFML Application
// Generated by cpx

#include <SFML/Graphics.hpp>
#include <SFML/Window.hpp>
#include <cmath>

int main() {
    // Create window
    sf::RenderWindow window(sf::VideoMode(800, 600), "%s");
    window.setFramerateLimit(60);

    // Create shapes
    sf::CircleShape circle(50.f);
    circle.setFillColor(sf::Color::Red);
    circle.setPosition(375.f, 275.f);
    circle.setOrigin(50.f, 50.f);

    sf::RectangleShape rectangle(sf::Vector2f(100.f, 60.f));
    rectangle.setFillColor(sf::Color::Blue);
    rectangle.setPosition(100.f, 100.f);

    // Animation variables
    float time = 0.f;
    sf::Clock clock;

    // Main loop
    while (window.isOpen()) {
        // Event handling
        sf::Event event;
        while (window.pollEvent(event)) {
            if (event.type == sf::Event::Closed) {
                window.close();
            }
            if (event.type == sf::Event::KeyPressed) {
                if (event.key.code == sf::Keyboard::Escape) {
                    window.close();
                }
            }
        }

        // Update
        float dt = clock.restart().asSeconds();
        time += dt;

        // Animate circle (pulsing and color changing)
        float scale = 1.0f + 0.2f * std::sin(time * 3.0f);
        circle.setScale(scale, scale);

        sf::Uint8 r = static_cast<sf::Uint8>(128 + 127 * std::sin(time * 2.0f));
        sf::Uint8 g = static_cast<sf::Uint8>(128 + 127 * std::sin(time * 2.5f));
        sf::Uint8 b = static_cast<sf::Uint8>(128 + 127 * std::sin(time * 3.0f));
        circle.setFillColor(sf::Color(r, g, b));

        // Animate rectangle (rotating)
        rectangle.rotate(60.f * dt);

        // Render
        window.clear(sf::Color(30, 30, 40));
        window.draw(rectangle);
        window.draw(circle);
        window.display();
    }

    return 0;
}
`, projectName, projectName)
}

func (t *SFMLTemplate) generateCMakeLists(projectName string, cppStandard int) string {
	return fmt.Sprintf(`cmake_minimum_required(VERSION 3.16)
project(%s VERSION 0.1.0 LANGUAGES CXX)

set(CMAKE_CXX_STANDARD %d)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)

# Find SFML
find_package(SFML COMPONENTS system window graphics CONFIG REQUIRED)

# Add executable
add_executable(${PROJECT_NAME}
    src/main.cpp
)

target_include_directories(${PROJECT_NAME} PRIVATE
    ${CMAKE_CURRENT_SOURCE_DIR}/include
)

target_link_libraries(${PROJECT_NAME} PRIVATE
    sfml-system
    sfml-window
    sfml-graphics
)

# Copy compile_commands.json to project root
if(CMAKE_EXPORT_COMPILE_COMMANDS)
    add_custom_target(copy_compile_commands ALL
        ${CMAKE_COMMAND} -E copy_if_different
        ${CMAKE_BINARY_DIR}/compile_commands.json
        ${CMAKE_SOURCE_DIR}/compile_commands.json
    )
endif()
`, projectName, cppStandard)
}

func (t *SFMLTemplate) generateReadme(projectName string) string {
	return fmt.Sprintf(`# %s

A multimedia application built with SFML (Simple and Fast Multimedia Library).

## Building

`+"```"+`bash
cpx build
`+"```"+`

## Running

`+"```"+`bash
cpx run
`+"```"+`

## Features

- Window with 60 FPS frame limiting
- Animated circle with pulsing effect
- Color-changing shapes
- Rotating rectangle
- Event handling (keyboard, window close)

## Controls

- **ESC**: Exit application

## Dependencies

- SFML (Graphics, Window, System)

## SFML Modules

SFML provides several modules:
- **System**: Vectors, time, threads
- **Window**: Window management, input
- **Graphics**: 2D rendering, shapes, sprites
- **Audio**: Sound, music playback
- **Network**: TCP/UDP sockets

## License

MIT
`, projectName)
}
