package project_templates

import (
	"fmt"

	"github.com/ozacod/cpx/internal/pkg/templates"
)

func init() {
	RegisterTemplate(&RaylibTemplate{})
}

// RaylibTemplate generates a Raylib game application
type RaylibTemplate struct {
	BaseTemplateHelper
}

func (t *RaylibTemplate) Name() string {
	return "Raylib"
}

func (t *RaylibTemplate) Description() string {
	return "Game application with Raylib library"
}

func (t *RaylibTemplate) Dependencies() []string {
	return []string{"raylib", "glfw3"}
}

func (t *RaylibTemplate) Generate(config TemplateConfig) error {
	projectName := config.ProjectName

	// Create directory structure
	dirs := []string{
		"include/" + projectName,
		"src",
		"assets",
		"docs",
	}
	if err := t.CreateProjectStructure(projectName, dirs); err != nil {
		return err
	}

	// Generate main.cpp
	mainCpp := t.generateMainCpp(projectName)
	if err := t.WriteFile(projectName, "src/main.cpp", mainCpp); err != nil {
		return err
	}

	// Generate version header
	versionHpp := templates.GenerateVersionHpp(projectName, "0.1.0")
	if err := t.WriteFile(projectName, "include/"+projectName+"/version.hpp", versionHpp); err != nil {
		return err
	}

	// Generate build system files (vcpkg only)
	cmakeLists := t.generateCMakeLists(projectName, config.CppStandard)
	if err := t.WriteFile(projectName, "CMakeLists.txt", cmakeLists); err != nil {
		return err
	}
	cmakePresets := templates.GenerateCMakePresets()
	if err := t.WriteFile(projectName, "CMakePresets.json", cmakePresets); err != nil {
		return err
	}
	if err := t.SetupVcpkg(projectName, t.Dependencies()); err != nil {
		return fmt.Errorf("failed to setup vcpkg: %w", err)
	}

	// Generate common files
	if err := t.GenerateCommonFiles(config); err != nil {
		return err
	}

	// Generate README
	readme := t.generateReadme(projectName)
	if err := t.WriteFile(projectName, "README.md", readme); err != nil {
		return err
	}

	// Initialize git
	_ = t.InitGitRepo(projectName)

	t.PrintSuccess(projectName)
	return nil
}

func (t *RaylibTemplate) generateMainCpp(projectName string) string {
	return fmt.Sprintf(`// %s - Raylib Application
// Generated by cpx

#include <raylib.h>

int main() {
    // Initialization
    const int screenWidth = 800;
    const int screenHeight = 450;

    InitWindow(screenWidth, screenHeight, "%s");

    // Define ball position and velocity
    Vector2 ballPosition = { screenWidth / 2.0f, screenHeight / 2.0f };
    Vector2 ballVelocity = { 5.0f, 4.0f };
    float ballRadius = 20.0f;
    Color ballColor = RED;

    SetTargetFPS(60);

    // Main game loop
    while (!WindowShouldClose()) {
        // Update
        ballPosition.x += ballVelocity.x;
        ballPosition.y += ballVelocity.y;

        // Bounce off walls
        if (ballPosition.x >= screenWidth - ballRadius || ballPosition.x <= ballRadius) {
            ballVelocity.x *= -1.0f;
            ballColor = (Color){
                static_cast<unsigned char>(GetRandomValue(50, 255)),
                static_cast<unsigned char>(GetRandomValue(50, 255)),
                static_cast<unsigned char>(GetRandomValue(50, 255)), 255 };
        }
        if (ballPosition.y >= screenHeight - ballRadius || ballPosition.y <= ballRadius) {
            ballVelocity.y *= -1.0f;
            ballColor = (Color){
                static_cast<unsigned char>(GetRandomValue(50, 255)),
                static_cast<unsigned char>(GetRandomValue(50, 255)),
                static_cast<unsigned char>(GetRandomValue(50, 255)), 255 };
        }

        // Draw
        BeginDrawing();
            ClearBackground(RAYWHITE);

            DrawCircleV(ballPosition, ballRadius, ballColor);
            DrawText("Welcome to %s!", 10, 10, 20, DARKGRAY);
            DrawText("Press ESC to exit", 10, 40, 16, GRAY);
            DrawFPS(screenWidth - 100, 10);

        EndDrawing();
    }

    // De-Initialization
    CloseWindow();

    return 0;
}
`, projectName, projectName, projectName)
}

func (t *RaylibTemplate) generateCMakeLists(projectName string, cppStandard int) string {
	return fmt.Sprintf(`cmake_minimum_required(VERSION 3.16)
project(%s VERSION 0.1.0 LANGUAGES CXX)

set(CMAKE_CXX_STANDARD %d)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)

# Find Raylib and GLFW
find_package(raylib CONFIG REQUIRED)
find_package(glfw3 CONFIG REQUIRED)

# Add executable
add_executable(${PROJECT_NAME}
    src/main.cpp
)

target_include_directories(${PROJECT_NAME} PRIVATE
    ${CMAKE_CURRENT_SOURCE_DIR}/include
)

target_link_libraries(${PROJECT_NAME} PRIVATE
    raylib
    glfw
)

# macOS frameworks
if(APPLE)
    target_link_libraries(${PROJECT_NAME} PRIVATE
        "-framework IOKit"
        "-framework Cocoa"
        "-framework OpenGL"
    )
endif()

# Copy compile_commands.json to project root
if(CMAKE_EXPORT_COMPILE_COMMANDS)
    add_custom_target(copy_compile_commands ALL
        ${CMAKE_COMMAND} -E copy_if_different
        ${CMAKE_BINARY_DIR}/compile_commands.json
        ${CMAKE_SOURCE_DIR}/compile_commands.json
    )
endif()
`, projectName, cppStandard)
}

func (t *RaylibTemplate) generateReadme(projectName string) string {
	return fmt.Sprintf(`# %s

A game application built with Raylib.

## Building

`+"```"+`bash
cpx build
`+"```"+`

## Running

`+"```"+`bash
cpx run
`+"```"+`

## Features

- Simple game loop with 60 FPS
- Ball bouncing animation
- Color changes on collision
- FPS counter display

## Controls

- **ESC**: Exit application

## Dependencies

- Raylib

## License

MIT
`, projectName)
}
